vocab_path: /home/tommaso/prova/data/vocab.txt
operation_path: /home/tommaso/prova/data/operations.txt
train_path: /home/tommaso/prova/data/toyset.txt
num_workers: 2
num_operations: 500
num_iters: 500
min_frequency: 10
mp_thd: 0.5
